### PR TITLE
Add output plugin and parser plugin support

### PR DESCRIPTION
**Pull request by toyokazu**
Dear yuuna,

I added output plugin and modify input plugin to support parser plugin (format option). Test codes are not implemented yet. Are you interested in merging it? The purposes of adding output plugin are to support data conversion by using Parser like fluent-plugin-xml-parser and uploading log files via MQTT.

https://github.com/toyokazu/fluent-plugin-xml-parser

Since many functions are added in this version, if you don't like to merge it, I'd like to publish new gem as the other name, for example, fluent-plugin-mqtt-io.

I'd like to have your feedback.
## Best Regards,

Toyokazu Akiyama

### CODE REVIEW

**Comment by toyokazu** [comment]
I am sorry that my request has conflicts and again Output Plugin request is already submitted from other person ;) So, I'd like to close this issue. Do you plan to merge the other output plugin request? If so, I'd like to resolve conflicts against the latest version.

**Comment by toyokazu** [comment]
I am sorry I can not wait your feedback. Since I want to publish current version at rubygems.org for our convenience, I already published fluent-plugin-mqtt-io. In the document (README.md), your project is referred.

Best Regards

**Comment by yuuna** [comment]
Hi I write out plugin as MQTT ways.

Please check my code.
Thanks.

**Comment by toyokazu** [comment]
Hello,

Thank you for your feedback.
I am not sure why you need MQTT message upper limit in this plugin.
I think that it is better to leave such kind of limitation at MQTT broker/client library level or fluentd level (buffer_chunk_limit). By adding another limitation the end user may be confused because they can not find the place to configure.

In this plugin, just catch the server side or client side error and provide error messages to the end users may be the best way, I guess.

Best

**Pull request closed without merging**
